export const siteConfig = {
  name: "Dushan Kavishka - Coastal & Civil Engineer",
  authorName: "Dushan Kavishka",
  username: "dushan-kavishka",
  description:
    "Dushan Kavishka - Graduate Research Assistant in Coastal and Port Engineering at the University of North Florida. Explore my research, experience, and projects in coastal, hydraulic, and civil engineering.",
  url: "https://dushankavishka.com",
  links: {
    linkedin: "https://linkedin.com/in/dushan-kavishka",
    templateRepo: "https://github.com/namanbarkiya/minimal-next-portfolio",
    email: "dushanmkdk@gmail.com",
    phone: "+1 (904) 422-6735",
  },
  ogImage: "/profile-img.jpg",
  iconIco: "/profile-img.jpg",
  logoIcon: "/profile-img.jpg",
  keywords: [
    "Dushan Kavishka",
    "Civil Engineer",
    "Coastal Engineer",
    "Port Engineer",
    "Water Resources Engineer",
    "Delft3D",
    "MIKE",
    "ANSYS Fluent",
    "HEC-HMS",
    "MATLAB",
    "Coastal Engineering",
    "Numerical Modeling",
    "University of North Florida",
    "University of Moratuwa",
    "Graduate Research Assistant",
  ],
};
